version: "3.8"

services:
  hr_management_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - hr_management_network
networks:
  hr_management_network:
    external: true