version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hr_management
    expose:
      - "8081"
    env_file:
      - .env
    networks:
      - backend
networks:
  backend: