spring.application.name=hr_management
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=SENIORDEV
spring.datasource.password=SENIORDEV
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8081
server.servlet.context-path=/hr-management
#actutor
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#jwt
jwt.secret=8a7c9e3b1d5f6a9c8e7d4c2b1a3f5e6d8c7b9a1f2e3d4c5b6a7c8d9e1f2a3b4
#log
#logging.level.org.springframework.security=TRACE